import subprocess
import json

def scan_username(username, use_sherlock=False):
    """
    Scans for a username across multiple platforms.
    If use_sherlock is True, attempts to run the actual Sherlock CLI tool.
    Otherwise, uses a fast, simulated mock scanner suitable for a prototype.
    """
    if use_sherlock:
        try:
            # Note: Requires the Sherlock CLI to be installed (e.g. `pip install sherlock-project`)
            # Running Sherlock takes several minutes, which might not be ideal for a quick demo.
            print(f"Running actual Sherlock scan for {username}...")
            # We run it and pipe output to a JSON file
            result = subprocess.run(
                ["sherlock", username, "--print-found", "--json", f"{username}.json"],
                capture_output=True, text=True
            )
            
            # Read the output JSON file generated by Sherlock
            try:
                with open(f"{username}.json", 'r') as f:
                    data = json.load(f)
                
                found_platforms = []
                for platform, details in data.items():
                    found_platforms.append({
                        "platform": platform,
                        "url": details.get("url_user", ""),
                        "status": "Found"
                    })
                return found_platforms
            except FileNotFoundError:
                print("Sherlock output file not found. Falling back to mock data.")
                return get_mock_username_data(username)
                
        except Exception as e:
            print(f"Sherlock scan failed ({e}). Falling back to mock data.")
            return get_mock_username_data(username)
    else:
        # Fast simulated scanning for prototype purposes (Instant Demo!)
        return get_mock_username_data(username)

def get_mock_username_data(username):
    """
    Returns mock platform presence data for the given username.
    """
    # Simple logic: 'ghost' returns nothing, anything else returns some simulated hits
    if username.lower() == 'ghost':
        return []
        
    return [
        {
            "platform": "GitHub",
            "url": f"https://github.com/{username}",
            "status": "Found"
        },
        {
            "platform": "Twitter",
            "url": f"https://twitter.com/{username}",
            "status": "Found"
        },
        {
            "platform": "Instagram",
            "url": f"https://instagram.com/{username}",
            "status": "Found"
        },
        {
            "platform": "Reddit",
            "url": f"https://reddit.com/user/{username}",
            "status": "Found"
        }
    ]

# For testing this script independently
if __name__ == "__main__":
    print(scan_username("johndoe"))
